/**
 * VoIP Service
 * Handles VoIP call room registration, Socket.IO integration, and responder notification
 */

import { io, Socket } from 'socket.io-client';
import { apiClient } from './api-config';

const SOCKET_URL = process.env.EXPO_PUBLIC_SOCKET_URL || 'http://localhost:3001';

export interface VoIPRoomData {
  room_name?: string; // Optional - will be generated by server
  hotline_id: string;
  user_id?: number;
  user_name?: string;
  latitude?: number;
  longitude?: number;
  priority?: number;
}

export interface VoIPRoomResponse {
  id: number;
  room_name: string;
  hotline_id: string;
  user_id: number;
  user_name: string;
  latitude?: number;
  longitude?: number;
  status: 'active' | 'ended';
  created_at: string;
  responder_notified: boolean;
}

type ApiBody = {
  success?: boolean;
  message?: string;
  data?: VoIPRoomResponse;
  room?: VoIPRoomResponse;
  id?: number;
  room_name?: string;
  hotline_id?: string;
  user_id?: number;
  user_name?: string;
  latitude?: number | null;
  longitude?: number | null;
  status?: string;
  created_at?: string;
  responder_notified?: boolean;
};

function parseVoIPRoomRecord(
  body: ApiBody,
  fallback?: Partial<VoIPRoomData>,
): VoIPRoomResponse {
  const source = body.data ?? body.room ?? body;

  return {
    id: Number(source.id),
    room_name: String(source.room_name ?? fallback?.room_name ?? ''),
    hotline_id: String(source.hotline_id ?? fallback?.hotline_id ?? ''),
    user_id: Number(source.user_id ?? fallback?.user_id ?? 0),
    user_name: String(source.user_name ?? fallback?.user_name ?? ''),
    latitude:
      source.latitude != null && String(source.latitude) !== ''
        ? Number(source.latitude)
        : fallback?.latitude,
    longitude:
      source.longitude != null && String(source.longitude) !== ''
        ? Number(source.longitude)
        : fallback?.longitude,
    status: (source.status ?? 'active') as 'active' | 'ended',
    created_at: String(source.created_at ?? new Date().toISOString()),
    responder_notified: Boolean(source.responder_notified ?? false),
  };
}

function assertSuccess(body: ApiBody, fallbackMessage: string): void {
  if (body.success === false) {
    throw new Error(body.message ?? fallbackMessage);
  }
}

export const voipService = {
  socket: null as Socket | null,

  /**
   * Initialize Socket.IO connection
   */
  connectSocket(): Socket {
    if (!this.socket) {
      this.socket = io(SOCKET_URL, {
        transports: ['websocket'],
        reconnection: true,
        reconnectionDelay: 1000,
        reconnectionAttempts: 5
      });

      this.socket.on('connect', () => {
        console.log('Socket.IO connected');
      });

      this.socket.on('disconnect', () => {
        console.log('Socket.IO disconnected');
      });

      this.socket.on('connect_error', (error) => {
        console.error('Socket.IO connection error:', error);
      });
    }
    return this.socket;
  },

  /**
   * Disconnect Socket.IO connection
   */
  disconnectSocket(): void {
    if (this.socket) {
      this.socket.disconnect();
      this.socket = null;
    }
  },

  /**
   * Register as a responder
   */
  registerResponder(responderId: number, responderName: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const socket = this.connectSocket();
      
      socket.emit('register_responder', {
        responder_id: responderId,
        responder_name: responderName
      });

      socket.once('responder_registered', (response) => {
        if (response.success) {
          resolve();
        } else {
          reject(new Error(response.message));
        }
      });

      socket.once('call_error', (error) => {
        reject(new Error(error.message));
      });
    });
  },

  /**
   * Initiate a VoIP call (user side)
   */
  initiateCall(data: VoIPRoomData): Promise<{ room_id: number; room_name: string; queue_position: number }> {
    return new Promise((resolve, reject) => {
      const socket = this.connectSocket();
      
      socket.emit('initiate_call', {
        user_id: data.user_id,
        user_name: data.user_name,
        hotline_id: data.hotline_id,
        latitude: data.latitude,
        longitude: data.longitude,
        priority: data.priority || 1
      });

      socket.once('call_initiated', (response) => {
        if (response.success) {
          resolve({
            room_id: response.room_id,
            room_name: response.room_name,
            queue_position: response.queue_position
          });
        } else {
          reject(new Error(response.message));
        }
      });

      socket.once('call_error', (error) => {
        reject(new Error(error.message));
      });
    });
  },

  /**
   * Accept a call (responder side)
   */
  acceptCall(roomId: number): Promise<void> {
    return new Promise((resolve, reject) => {
      const socket = this.connectSocket();
      
      socket.emit('accept_call', { room_id: roomId });

      socket.once('call_accepted', (response) => {
        if (response.success) {
          resolve();
        } else {
          reject(new Error(response.message));
        }
      });

      socket.once('call_error', (error) => {
        reject(new Error(error.message));
      });
    });
  },

  /**
   * End a call
   */
  endCall(roomId: number): Promise<void> {
    return new Promise((resolve, reject) => {
      const socket = this.connectSocket();
      
      socket.emit('end_call', { room_id: roomId });

      socket.once('call_ended', (response) => {
        if (response.success) {
          resolve();
        } else {
          reject(new Error(response.message));
        }
      });

      socket.once('call_error', (error) => {
        reject(new Error(error.message));
      });
    });
  },

  /**
   * Listen for call assignments (responder side)
   */
  onCallAssigned(callback: (callData: any) => void): void {
    const socket = this.connectSocket();
    socket.on('call_assigned', callback);
  },

  /**
   * Listen for call acceptance (user side)
   */
  onCallAccepted(callback: (data: any) => void): void {
    const socket = this.connectSocket();
    socket.on('call_accepted', callback);
  },

  /**
   * Remove event listeners
   */
  off(event: string, callback?: (...args: any[]) => void): void {
    if (this.socket) {
      if (callback) {
        this.socket.off(event, callback);
      } else {
        this.socket.off(event);
      }
    }
  },

  /**
   * Register a new VoIP call room (fallback for PHP API)
   * @deprecated Use initiateCall() with Socket.IO instead
   */
  async registerRoom(data: VoIPRoomData): Promise<VoIPRoomResponse> {
    try {
      const response = await apiClient.post<ApiBody>(
        '/voip/register_room.php',
        data,
      );
      const body = response.data;
      assertSuccess(body, 'Failed to register VoIP room.');
      return parseVoIPRoomRecord(body, data);
    } catch (error) {
      console.error('Failed to register VoIP room:', error);
      throw error;
    }
  },

  /**
   * Update room status (e.g., when call ends)
   * @deprecated Use endCall() with Socket.IO instead
   */
  async updateRoomStatus(
    roomId: number,
    status: 'active' | 'ended',
  ): Promise<VoIPRoomResponse> {
    try {
      const response = await apiClient.post<ApiBody>(
        '/voip/update_room.php',
        { room_id: roomId, status },
      );
      const body = response.data;
      assertSuccess(body, 'Failed to update VoIP room status.');
      return parseVoIPRoomRecord(body);
    } catch (error) {
      console.error('Failed to update VoIP room status:', error);
      throw error;
    }
  },

  /**
   * Get active VoIP room for a user
   */
  async getActiveRoom(userId: number): Promise<VoIPRoomResponse | null> {
    try {
      const response = await apiClient.get<ApiBody>(
        '/voip/get_active_room.php',
        { params: { user_id: userId } },
      );
      const body = response.data;
      if (!body.data && !body.room) {
        return null;
      }
      assertSuccess(body, 'Failed to fetch active VoIP room.');
      return parseVoIPRoomRecord(body);
    } catch (error) {
      console.error('Failed to fetch active VoIP room:', error);
      return null;
    }
  },
};
